function rte_show_toolbar(html)
	{
	html.push('<table>');
		html.push('<tr>');
			html.push('<td style="padding: 0px;" id="rteformat">');
				html.push('<div style="height: 24px;">');
					html.push('<div style="padding: 4px;">');
						rte_show_dropdown_format(html);
					html.push('</div>');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;" id="rtefontface">');
				html.push('<div style="height: 24px;">');
					html.push('<div style="padding: 4px;">');
						rte_show_dropdown_face(html);
					html.push('</div>');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;" id="rte_fontsize">');
				html.push('<div style="height: 24px;">');
					html.push('<div style="padding: 4px;">');
						rte_show_dropdown_size(html);
					html.push('</div>');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;" id="rtefontcolor">');
				html.push('<div style="height: 24px;">');
					html.push('<div style="padding: 1px;">');
						rte_show_dropdown_color(html);
					html.push('</div>');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div style="padding-left: 2px; padding-right: 2px;">');
					html.push('<div class="rte_menu_separator">');
					html.push('</div>');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="bold" class="rte_button_m" title="Fett">');
					html.push('<img src="' + rte_image_path + 'format-text-bold.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="italic" class="rte_button_m" title="Kursiv">');
					html.push('<img src="' + rte_image_path + 'format-text-italic.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="underline" class="rte_button_m"title="Unterstrichen">');
					html.push('<img src="' + rte_image_path + 'format-text-underline.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div style="padding-left: 2px; padding-right: 2px;">');
					html.push('<div class="rte_menu_separator">');
					html.push('</div>');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="justifyleft" class="rte_button_m" title="Linksbündig">');
					html.push('<img src="' + rte_image_path + 'format-justify-left.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="justifycenter" class="rte_button_m" title="Zentriert">');
					html.push('<img src="' + rte_image_path + 'format-justify-center.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="justifyright" class="rte_button_m" title="Rechtsbündig">');
					html.push('<img src="' + rte_image_path + 'format-justify-right.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="justifyjustify" class="rte_button_m" title="Blocksatz">');
					html.push('<img src="' + rte_image_path + 'format-justify-fill.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div style="padding-left: 2px; padding-right: 2px;">');
					html.push('<div class="rte_menu_separator">');
					html.push('</div>');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="insertorderedlist" class="rte_button_m" title="Numerierung">');
					html.push('<img src="' + rte_image_path + 'orderedlist.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');


				html.push('<div id="insertunorderedlist" class="rte_button_m" title="Aufzählung">');
					html.push('<img src="' + rte_image_path + 'unorderedlist.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="outdent" class="rte_button_m" title="Einzug verkleinern">');
					html.push('<img src="' + rte_image_path + 'format-indent-less.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="indent" class="rte_button_m" title="Einzug vergrößern">');
					html.push('<img src="' + rte_image_path + 'format-indent-more.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div style="padding-left: 2px; padding-right: 2px;">');
					html.push('<div class="rte_menu_separator">');
					html.push('</div>');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="inserthorizontalrule" class="rte_button_m" title="Horizontale Linie">');
					html.push('<img src="' + rte_image_path + 'hr.gif" style="padding: 1px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div style="padding-left: 2px; padding-right: 2px;">');
					html.push('<div class="rte_menu_separator">');
					html.push('</div>');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('<div id="removeformat" class="rte_button_m" title="Formatierung entfernen">');
					html.push('<img src="' + rte_image_path + 'format.png" style="padding: 3px;">');
				html.push('</div>');
			html.push('</td>');
			html.push('<td style="padding: 0px; width: 100%;">');
				html.push('&nbsp;');
			html.push('</td>');
			html.push('<td id="charcounter" style="padding: 0px;" nowrap>');
				html.push('160 / 1');
			html.push('</td>');
			html.push('<td style="padding: 0px;">');
				html.push('&nbsp;');
			html.push('</td>');
		html.push('</tr>');
	html.push('</table>');
	}

